#!/usr/bin/env bash
# Concatenates the CSS sources into css/bundle.css (one render-blocking request).
# Run after editing any file below; the order is the cascade order.
set -euo pipefail

cd "$(dirname "$0")"

sources=(
  base.css
  utilities.css
  components/cursor.css
  components/pomodoro.css
  components/nav.css
  components/rail.css
  components/hero.css
  components/brands.css
  components/terminal.css
  components/skills.css
  components/projects.css
  components/diagrams.css
  components/cases.css
  components/why.css
  components/experience.css
  components/blog.css
  components/contact.css
  components/footer.css
  components/mascot.css
  components/keyboard.css
)

{
  echo "/* Generated by css/build.sh from the files in css/ — do not edit. */"
  for src in "${sources[@]}"; do
    printf '\n/* === %s === */\n' "$src"
    cat "$src"
  done
} > bundle.css
