// Generated by scripts/build-content.mjs from content/ — do not edit.
window.BLOG_NOTES = [
  {
    "slug": "oracle-select-for-update-wait-nowait",
    "type": "note",
    "title": "Oracle: SELECT FOR UPDATE WAIT vs NOWAIT",
    "excerpt": "Cómo bloquear una fila como máximo unos segundos (o fallar al instante) cuando otra transacción ya la tiene bloqueada.",
    "category": "Oracle",
    "categoryKey": [
      "oracle",
      "bases-de-datos"
    ],
    "tags": [
      "Oracle",
      "Concurrencia",
      "Locks"
    ],
    "date": "2026-09-26",
    "updated": "2026-09-26",
    "minutes": 1,
    "learning": [
      "distributed-systems"
    ],
    "relatedProject": null,
    "path": "blog/notes/oracle-select-for-update-wait-nowait.html"
  }
];
