// Generated by scripts/build-content.mjs from content/ — do not edit.
window.BLOG_NOTES = [
  {
    "slug": "claude-code-sandbox-usb-gh",
    "type": "note",
    "title": "Claude Code: cuando el sandbox no te deja ver algo",
    "excerpt": "Si adb no ve el teléfono o gh auth login no conecta, el problema puede ser el sandbox y no la red ni el cable.",
    "category": "IA",
    "categoryKey": [
      "ia",
      "herramientas"
    ],
    "tags": [
      "Claude Code",
      "Sandbox",
      "macOS"
    ],
    "date": "2026-09-26",
    "updated": "2026-09-26",
    "minutes": 1,
    "learning": [
      "ai-engineering"
    ],
    "relatedProject": null,
    "path": "blog/notes/claude-code-sandbox-usb-gh.html"
  },
  {
    "slug": "node-oracledb-maxlifetimesession-thick",
    "type": "note",
    "title": "node-oracledb: maxLifetimeSession no te salva de ORA-02399",
    "excerpt": "En Thick mode el pool no jubiló una sesión vencida. Contra CONNECT_TIME e IDLE_TIME, la defensa es reintentar en tu código.",
    "category": "Oracle",
    "categoryKey": [
      "oracle",
      "nestjs"
    ],
    "tags": [
      "Oracle",
      "node-oracledb",
      "Connection pool"
    ],
    "date": "2026-09-26",
    "updated": "2026-09-26",
    "minutes": 2,
    "learning": [
      "distributed-systems"
    ],
    "relatedProject": null,
    "path": "blog/notes/node-oracledb-maxlifetimesession-thick.html"
  },
  {
    "slug": "node-oracledb-njs-116-thick-mode",
    "type": "note",
    "title": "node-oracledb: NJS-116 y el verificador de contraseña 0x939",
    "excerpt": "Si Thin mode no puede autenticar por el verificador de contraseña, cambia a Thick mode con Instant Client.",
    "category": "Oracle",
    "categoryKey": [
      "oracle",
      "nestjs"
    ],
    "tags": [
      "Oracle",
      "Node.js",
      "node-oracledb"
    ],
    "date": "2026-09-26",
    "updated": "2026-09-26",
    "minutes": 1,
    "learning": [],
    "relatedProject": null,
    "path": "blog/notes/node-oracledb-njs-116-thick-mode.html"
  },
  {
    "slug": "openshift-reiniciar-deployment-sin-borrar-pods",
    "type": "note",
    "title": "OpenShift: reiniciar un deployment sin borrar pods a mano",
    "excerpt": "Un solo comando para que OpenShift levante pods nuevos y baje los viejos, sin hacer oc delete pod.",
    "category": "OpenShift",
    "categoryKey": [
      "openshift",
      "devops"
    ],
    "tags": [
      "OpenShift",
      "Kubernetes",
      "oc"
    ],
    "date": "2026-09-26",
    "updated": "2026-09-26",
    "minutes": 1,
    "learning": [
      "cloud-platform"
    ],
    "relatedProject": null,
    "path": "blog/notes/openshift-reiniciar-deployment-sin-borrar-pods.html"
  },
  {
    "slug": "oracle-ora-00054-a-http-409",
    "type": "note",
    "title": "Oracle: convertir ORA-00054 en un HTTP 409",
    "excerpt": "Con FOR UPDATE NOWAIT, una fila ocupada falla en milisegundos. Traduce ese error a 409 Conflict en vez de dejar que salga como 500.",
    "category": "Oracle",
    "categoryKey": [
      "oracle",
      "nestjs"
    ],
    "tags": [
      "Oracle",
      "NestJS",
      "Locks"
    ],
    "date": "2026-09-26",
    "updated": "2026-09-26",
    "minutes": 1,
    "learning": [
      "distributed-systems"
    ],
    "relatedProject": null,
    "path": "blog/notes/oracle-ora-00054-a-http-409.html"
  },
  {
    "slug": "oracle-select-for-update-wait-nowait",
    "type": "note",
    "title": "Oracle: SELECT FOR UPDATE WAIT vs NOWAIT",
    "excerpt": "Cómo bloquear una fila como máximo unos segundos (o fallar al instante) cuando otra transacción ya la tiene bloqueada.",
    "category": "Oracle",
    "categoryKey": [
      "oracle",
      "bases-de-datos"
    ],
    "tags": [
      "Oracle",
      "Concurrencia",
      "Locks"
    ],
    "date": "2026-09-26",
    "updated": "2026-09-26",
    "minutes": 1,
    "learning": [
      "distributed-systems"
    ],
    "relatedProject": null,
    "path": "blog/notes/oracle-select-for-update-wait-nowait.html"
  },
  {
    "slug": "oracle-validar-insert-sin-ejecutarlo",
    "type": "note",
    "title": "Oracle: validar un INSERT sin ejecutarlo con DBMS_SQL.PARSE",
    "excerpt": "Comprueba la sintaxis y los objetos de un DML contra la base real sin insertar nada ni consumir secuencias.",
    "category": "Oracle",
    "categoryKey": [
      "oracle",
      "bases-de-datos"
    ],
    "tags": [
      "Oracle",
      "PL/SQL",
      "DBMS_SQL"
    ],
    "date": "2026-09-26",
    "updated": "2026-09-26",
    "minutes": 1,
    "learning": [],
    "relatedProject": null,
    "path": "blog/notes/oracle-validar-insert-sin-ejecutarlo.html"
  }
];
